[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dprod-shared"
version = "0.1.0"
description = "Shared types and utilities for Dprod"
authors = ["Dprod Team <team@dprod.dev>"]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.0"
sqlalchemy = "^2.0.23"
uuid = "^1.30"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
