[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dprod-detection-engine"
version = "0.1.0"
description = "Project detection engine for Dprod"
authors = ["Dprod Team <team@dprod.dev>"]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.0"
dprod-shared = {path = "../shared", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
