name: Staging DB Migrations

on:
  workflow_dispatch: {}
  push:
    branches: ["staging"]
    paths:
      - "services/**"
      - "alembic/**"
      - "alembic.ini"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install deps
        run: |
          poetry config virtualenvs.create false
          poetry install --only=main --no-root

      - name: Run Alembic migrations
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: |
          alembic upgrade head


